version: "3"

services:
  db:
    hostname: postgres
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goapi
    ports:
      - 5432:5432
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - pgdata:/var/łib/postgresql/data

volumes:
  pgdata:
    driver: local
